import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#273044",
        "on-surface-variant": "#43474f",
        "tertiary-fixed": "#d6e3ff",
        "primary-fixed": "#d5e3ff",
        "surface-container": "#e9edff",
        "on-surface": "#121b2e",
        "background": "#f9f9ff",
        "on-secondary-fixed": "#261900",
        "surface-container-low": "#f1f3ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d9e2fc",
        "inverse-on-surface": "#edf0ff",
        "primary-container": "#062b55",
        "outline": "#747780",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#abc8fa",
        "surface-container-high": "#e1e8ff",
        "surface-tint": "#425f8c",
        "on-primary-container": "#7793c3",
        "on-primary-fixed-variant": "#2a4772",
        "on-tertiary-container": "#6e93d1",
        "on-primary-fixed": "#001b3c",
        "surface-bright": "#f9f9ff",
        "tertiary": "#001634",
        "outline-variant": "#c4c6d0",
        "surface-variant": "#d9e2fc",
        "surface": "#f9f9ff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary-container": "#002a59",
        "secondary-container": "#feca5a",
        "secondary-fixed": "#ffdea2",
        "on-background": "#121b2e",
        "on-secondary-container": "#745400",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#a9c7ff",
        "secondary": "#7a5900",
        "on-error-container": "#93000a",
        "surface-dim": "#d1daf4",
        "on-tertiary-fixed": "#001b3e",
        "on-secondary-fixed-variant": "#5c4200",
        "secondary-fixed-dim": "#f2bf50",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#1d4680",
        "primary": "#001634",
        "inverse-primary": "#abc8fa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.5rem",
        "space-4xl": "6rem",
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "gutter-desktop": "2rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter-tablet": "1.5rem",
        "max-width": "1280px",
      },
      fontFamily: {
        "body-sm": ["var(--font-plus-jakarta-sans)"],
        "display-lg-mobile": ["var(--font-outfit)"],
        "title-md": ["var(--font-plus-jakarta-sans)"],
        "display-lg": ["var(--font-outfit)"],
        "label-sm": ["var(--font-plus-jakarta-sans)"],
        "display-md-mobile": ["var(--font-outfit)"],
        "display-md": ["var(--font-outfit)"],
        "headline-lg": ["var(--font-outfit)"],
        "title-lg": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-plus-jakarta-sans)"],
        "headline-sm": ["var(--font-outfit)"],
        "label-md": ["var(--font-plus-jakarta-sans)"],
        "headline-md": ["var(--font-outfit)"],
        "body-lg": ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-md-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-md": ["44px", { lineHeight: "52px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
